DROP TABLE IF EXISTS Admin;
CREATE TABLE Admin (
	id INTEGER PRIMARY KEY,
	username TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL
);

DROP TABLE IF EXISTS Song;
CREATE TABLE Song (
	id INTEGER PRIMARY KEY,
	name TEXT UNIQUE NOT NULL,
	lyrics TEXT NOT NULL
);

DROP TABLE IF EXISTS EntrySong;
CREATE TABLE EntrySong (
	id INTEGER PRIMARY KEY REFERENCES Song(id)
);

DROP TABLE IF EXISTS UniversalPrayerSong;
CREATE TABLE UniversalPrayerSong (
	id INTEGER PRIMARY KEY REFERENCES Song(id)
);

DROP TABLE IF EXISTS OffertorySong;
CREATE TABLE OffertorySong (
	id INTEGER PRIMARY KEY REFERENCES Song(id)
);

DROP TABLE IF EXISTS CommunionSong;
CREATE TABLE CommunionSong (
	id INTEGER PRIMARY KEY REFERENCES Song(id)
);

DROP TABLE IF EXISTS SendingSong;
CREATE TABLE SendingSong (
	id INTEGER PRIMARY KEY REFERENCES Song(id)
);

INSERT INTO Admin VALUES ('admin', 'secretpassword');